### ISSUE TITLE
Typo on error message when user does not open a document before selecting tool

### ISSUE THREAD

**Issue by rrothner** [Peanut-Butter-OSS/PDF-Marking-Tool#2]
To reproduce:
1. Open Acrobat DC
2. Do not open a file, go to Tools and select Add On Tools
3. Click on the No Document to Mark message

No active document found. Cannot initialise the onscreen marking tool. Note, **initilization** only occurs when opening Acrobat. Please close Acrobat and **recopen** the document.

![image](https://user-images.githubusercontent.com/9681051/96997439-116f7f80-1532-11eb-84a9-a1dfb491232e.png)

**Comment by gregfullard** [comment]
Resolved
